# Generated by Django 5.1.5 on 2025-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="provider",
            name="provider",
            field=models.CharField(
                choices=[("google", "Google"), ("naver", "naver"), ("kakao", "Kakao")],
                max_length=20,
            ),
        ),
    ]
