# Generated by Django 5.1.5 on 2025-02-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nick_name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
