# Generated by Django 5.1.5 on 2025-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
