# Generated by Django 5.1.5 on 2025-02-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Tags",
        ),
        migrations.RenameModel(
            old_name="WebtoonTag",
            new_name="WebtoonTags",
        ),
    ]
