# Generated by Django 5.1.5 on 2025-02-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webtoontag",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="webtoontag",
            name="webtoon",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="Webtoon",
        ),
        migrations.DeleteModel(
            name="WebtoonTag",
        ),
    ]
