# Generated by Django 5.1.5 on 2025-02-16 21:17

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("webtoons", "0002_remove_webtoontag_tag_remove_webtoontag_webtoon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("genre", "장르"),
                            ("matter", "소재"),
                            ("atmosphere", "분위기"),
                            ("relation", "관계"),
                            ("job", "직업"),
                            ("male character", "남캐"),
                            ("female character", "여캐"),
                            ("character", "캐릭터성"),
                            ("top/bottom", "00공수"),
                            ("etc", "기타"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Webtoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=50)),
                ("thumbnail", models.ImageField(upload_to="webtoons/thumbnails")),
                ("age_rating", models.CharField(max_length=10)),
                ("publication_day", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=True)),
                ("webtoon_url", models.URLField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("naver", "네이버"),
                            ("kakaopage", "카카오페이지"),
                            ("kakao", "카카오웹툰"),
                            ("others", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "serialization_cycle",
                    models.CharField(
                        choices=[
                            ("1weeks", "1주"),
                            ("2weeks", "2주"),
                            ("10days", "10일"),
                            ("20days", "20일"),
                            ("month", "한달"),
                            ("etc.", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "serial_day",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("mon", "월요일"),
                            ("tue", "화요일"),
                            ("wed", "수요일"),
                            ("thu", "목요일"),
                            ("fri", "금요일"),
                            ("sat", "토요일"),
                            ("sun", "일요일"),
                        ],
                        max_length=27,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebtoonTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webtoons.tag"
                    ),
                ),
                (
                    "webtoon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webtoon_tags",
                        to="webtoons.webtoon",
                    ),
                ),
            ],
        ),
    ]
