# Generated by Django 5.1.5 on 2025-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoon",
            name="serialization_cycle",
            field=models.CharField(
                choices=[
                    ("1weeks", "1주"),
                    ("2weeks", "2주"),
                    ("10days", "10일"),
                    ("20days", "20일"),
                    ("month", "한달"),
                    ("etc", "기타"),
                ],
                max_length=20,
            ),
        ),
    ]
