# Generated by Django 5.1.5 on 2025-02-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0004_alter_webtoon_serialization_cycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    ("genre", "장르"),
                    ("matter", "소재"),
                    ("atmosphere", "분위기"),
                    ("relation", "관계"),
                    ("job", "직업"),
                    ("male character", "남캐"),
                    ("female character", "여캐"),
                    ("character", "캐릭터성"),
                    ("top/bottom", "00공수"),
                    ("etc", "기타"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
