# Generated by Django 5.1.5 on 2025-02-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0005_alter_tag_category_alter_tag_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=100),
        ),
    ]
