# Generated by Django 5.1.6 on 2025-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0006_alter_tag_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="webtoon",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
