# Generated by Django 5.1.6 on 2025-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0008_alter_webtoon_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoon",
            name="platform",
            field=models.CharField(
                choices=[
                    ("all", "전체"),
                    ("naver", "네이버"),
                    ("kakaopage", "카카오페이지"),
                    ("kakao", "카카오웹툰"),
                    ("postype", "포스타입"),
                    ("others", "기타"),
                ],
                max_length=20,
            ),
        ),
    ]
