# Generated by Django 5.1.6 on 2025-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webtoons", "0009_alter_webtoon_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoon",
            name="thumbnail",
            field=models.URLField(),
        ),
    ]
